### ISSUE TITLE
eventbrite

### ISSUE THREAD

**Issue by katieannemills** [lmguzman/2016-01-29-UBC#3]
heya - can we get the eventbrite code into `index.html` plz? Then we will be 100% good to go :)

**Comment by lmguzman** [comment]
Hey, where can I find this code on the website?? (I dont know where to find it :S)

**Comment by katieannemills** [comment]
I think it's the number part of the url for your event, which would have been sent to you in an email after you made it. Try that out and see if the event registration widget appears on your page - if not we'll have to dig a bit deeper, let me know!

**Comment by lmguzman** [comment]
Yah! success!

**Comment by katieannemills** [comment]
Looks good - but I see you changed something down in the guts of the eventbrite widget while we were trying to get this to work; I'll send a PR in just a second....

**Comment by katieannemills** [comment]
yup that's got it now :) sorry this part was a bit circuitous, hopefully it'll be clearer next time :)
